services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/Users/jaydeep.parmar/Documents/rabbitmq/data/
      - ~/.docker-conf/rabbitmq/log/:/Users/jaydeep.parmar/Documents/rabbitmq/log/
    networks:
      - docker_network

networks:
  docker_network: {}
