services:
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker-volume/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker-volume/rabbitmq/log/:/var/log/rabbitmq/
      - ./docker-setup/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker-setup/definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - docker_network

  postgres:
    image: 'postgres:alpine'
    container_name: 'db'
    restart: always
    environment:
      - POSTGRES_USER=jduser
      - POSTGRES_PASSWORD=jdpassword
    ports:
      - 5432:5432
    volumes:
      - ./docker-volume/postgres/data/:/var/lib/postgresql/data/
      - ./docker-setup/setup.sql:/docker-entrypoint-initdb.d/setup.sql

networks:
  docker_network:
