spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jduser
    password: jdpassword
    url: jdbc:postgresql://127.0.0.1:5432/postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue-name: account-updates
